### ISSUE TITLE
Currently we assume that $wgScriptPath is ""

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#117]
The default value is "/wiki". Our "" is incompatible with the default, and will cause page signing and witness to fail.

**Comment by rht** [comment]
This also applies to all external API calls, done by data-accounting-external-verifier and VerifyPage.

**Comment by it-spiderman** [comment]
There is also another variable: `$wgArticlePath`, this controls whether the URL will be `domain/wiki/index.php?title=Main_Page` or `domain/wiki/iMain_Page`. I saw in `VErfiyPage` that `index.php` part is expected, and i assume i would fail if latter of the URLs was used.

For external tools to really know what value is set here, they must be configured with this value. Some config need to tell them, script path is this, and article path is that. How external tools know about the URL of the wiki at all?

Other way is to make sure in the container that values for these are what extenal tools expect, but this is error-prone, as sooner or later someone will change the values of these configs.

**Comment by pwirth** [comment]
Is there specific code snippets, where you need the script path?

mediawiki itself exposes some functions and configs in JS.
    mw.util.wikiScript( 'rest' ) // gives you the relative path to the rest.php /w/rest.php, /wiki/rest.php etc.

if you can not execute this function this can also be retreived by the following code:
    mw.config.values.wgScriptPath + '/rest.php';

the absolute path can be retrieved like:
    mw.config.values.wgServer + mw.config.values.wgScriptPath + '/rest.php'; // -> https://myserver/wiki/rest.php

**Comment by rht** [comment]
The external verifier doesn't have access to `mw.config.values.*`.

**Comment by rht** [comment]
OK, at least the signing and witnessing are solvable with `mw.config.values.wgScriptPath`.

**Comment by pwirth** [comment]
I am not sure how this works, but for external services you may either have to explicitly configure the path to rest per wiki
`https://myserver/wiki/rest.php`
or route the url to the rest api through the thing, that lets the external verifier know, that there is a wiki that needs verification

**Comment by FantasticoFox** [comment]
It was changed to use localhost:9352/rest.php/data_accounting/ and has been solved way back.
