### ISSUE TITLE
Add types (code quality)

### ISSUE THREAD

**Issue by JeroenDeDauw** [inblockio/mediawiki-extensions-Aqua#150]
The code will be easier to understand and maintain if types are added. This will also increase confidence in correctness.

* Parameter types
* Return types
* Property types

This should be possible and easy to do (albeit still require work/effort) in most places. There might be some exceptions, but applying this in most places is sufficient to get most of the benefit. 

Just using PHPs type capabilities will go a long way, though you could consider also using doc comments for more complex types like arrays. Example: https://github.com/ProfessionalWiki/ExternalContent/blob/master/src/Adapters/FileFetcher/DomainCredentials.php. These types are understood by various PHP tools like the static analysis ones already set up for this extension and IDEs like PhpStorm.

**Comment by it-spiderman** [comment]
@rht progress so far looks good.

Whats mostly needed here is typing of params in the signature
`function dummy( string $key, array $value, ?string $comment = '' )`

Typing of return values whenever possible
`function dummy( ): string {}`

For the config variables and services in generally, its sometimes really hard to type them.
For services, we usually specify the type in the comment
```
/** @var Hasher $hasher */
$hasher = MediaWikiService::getInstance()->getService( 'DAHasher' );
```
However, if this does not work with psalm, im not sure how to type this

For config vars, i guess (again to work with psalm) way you did it is ok
`(string) $config->get( 'stuff' );`

One important note. As per the last state im aware of, MediaWiki CI on gerrit does not like specifying params and return types as `string` and `bool`. I cannot tell why this is, but its somethign to keep in mind if extension is ever moved to gerrit.

**Comment by FantasticoFox** [comment]
We would like to offload that one to increase our focus on the protocol

**Comment by FantasticoFox** [comment]
@pwirth can you take that on?

**Comment by pwirth** [comment]
started with this task in https://github.com/inblockio/DataAccounting/pull/213

with following commands one can execute the codesniffer test and auto-fixes via commandline in the repo before comitting:
composer test
composer fix

**Comment by FantasticoFox** [comment]
Moving target, put it to v1.2 @pwirth can we measure how much is left?

**Comment by pwirth** [comment]
there is no automatic test of missing annotations that i am aware of.
ill do the API's next then

**Comment by FantasticoFox** [comment]
Guardian is written in Rust and therefore uses types

**Comment by JeroenDeDauw** [comment]
You switched away from MediaWiki completely?

**Comment by FantasticoFox** [comment]
No. We still have the Mediawiki as the backend for our prototype. We developed a security component to exchange Aqua-Chains between containers using 'Guardians' written in Rust.

We will open source that code soon. It allows to share pages based on Aqua-Contracts which are signed by wallets.
