### ISSUE TITLE
Inject global state (code quality)

### ISSUE THREAD

**Issue by JeroenDeDauw** [inblockio/mediawiki-extensions-Aqua#154]
Direct usages of global state make testing very difficult, since such code does not have seams that allow changing its behavior.

Examples of global access:

* `global $wgWhatever`
* `someFunction`, where the function accesses any global state
* `SomeClass::SomeMethod`, where the method accesses any global state
    * Anything talking to `MediaWikiServices::getInstance()`

Instead: inject global values in the constructor. This might require the creation of new services to inject. Example: persistence services https://github.com/inblockio/DataAccounting/issues/151

https://github.com/inblockio/DataAccounting/pull/153 contains example refactoring. Step-by-step in multiple commits. 
* https://github.com/inblockio/DataAccounting/pull/153/commits/285ce3a2f792dc59c81e1ee365815f9350bd520f
* https://github.com/inblockio/DataAccounting/pull/153/commits/e2e587d5a44b0d4fee231991b965dd5086ae89c4
* https://github.com/inblockio/DataAccounting/pull/153/commits/37d9e953db2643566e42d56501460fd9d89826f4
* 2 TODOs about remaining global access in `PageVerificationBuilder` https://github.com/inblockio/DataAccounting/pull/153/commits/366b3898edd7db45ba2aeb09428187c28087e832

**Comment by JeroenDeDauw** [comment]
This is very important for testability, especially if we want to have a healthy ratio of unit and integration tests.

**Comment by FantasticoFox** [comment]
This is required to be done before we extend our unit tests. This needs to be done when we start to do the Unit-Test coverage.

**Comment by it-spiderman** [comment]
I would add here:
- no global functions, no any functions outside of classes that are called directly (eg. `injectSignatureToPage`)
- no manual includes (`require_once __DIR__ . "/../ApiUtil.php"; require_once __DIR__ . "/../Util.php"; require 'vendor/autoload.php';`) => create services out of these

**Comment by it-spiderman** [comment]
Let me know if examples on how to fix this are needed

**Comment by rht** [comment]
I definitely need an example for dealing with those `require_once ...`'s.

**Comment by it-spiderman** [comment]
I think the best way to give example is refactor one of those files (eg. Utils.php), and make a commit. I will paste the commit here once done

**Comment by it-spiderman** [comment]
I started the commit, with example: https://github.com/inblockio/DataAccounting/commit/1d77e062d89e3d814af62395b5bc8b975dbcda0a

At the moment this commit will break stuff, as i did not refactor all places in the code that still use the "global" functions
But general idea is:
`getHashSum()` becomes `MediaWikiServices::getInstance()->getService( 'DataAccountingUtil' )->getHashSum()`

Can you continue this refactoring with this?

**Comment by rht** [comment]
Yes, that is a sufficient lead. If I have more questions, I will ask here.

**Comment by FantasticoFox** [comment]
@pwirth can we hand this refactor to you? This is applying to Utils and APIUtils in /include.

We compiled a checklist to get work against a measurable goal:
- [ ] getHashSum
- [ ] generateRandomHash
- [ ] generateDomainId
- [ ] getDomainId
- [ ] editPageContent
- [ ] get_page_all_revs
- [ ] getPageChainHeight
- [ ] requestMerkleProof
- [ ] getWitnessData
- [ ] getMaxWitnessEventId

**Comment by pwirth** [comment]
sure

**Comment by it-spiderman** [comment]
Since Util.php and ApiUtils.php are now gone completely, i think we can close this
