### ISSUE TITLE
[REFACTOR] Scheduled backups

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#180]
As a User I would like to keep a scheduled backup of my PKC so I don't lose data if there is a bug in the code.

Acceptance criteria:

- [ ] Functionality similar to previously working version
- [ ] Ability to specify number of backups to keep
- [ ] User can specify backup frequency
- [ ] Manual backups are still possible
- [ ] I am warned if my backup version is incompatible to my current PKC deployment on restore

**Comment by FantasticoFox** [comment]
See related issue in micro-PKC https://github.com/inblockio/micro-PKC/issues/88

**Comment by 0xc0000007b** [comment]
https://github.com/inblockio/DataAccounting/issues/109

**Comment by FantasticoFox** [comment]
Would like to see the refactor going into our main branch after ensuring it has the same behavior on restoring and storing in /mountpoint/backup

**Comment by rht** [comment]
@0xc0000007b make sure to this solution in the scheduled-backup branch (https://github.com/inblockio/MediaWiki_Backup/commit/0c161b9bd7f3b8963301032af12c41bb8fb3f013) to ensure that `sed` follows symlinks.

**Comment by FantasticoFox** [comment]
Until requested by a customer this will not be fixed.
