### ISSUE TITLE
Design: MediaWiki handling page encryption / decryption

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#197]
Requirements:
- iteration one: single user-encryption / decryption
- iteration two: multi-user-encryption / decryption

Design proposal:
- using existing battle proven libraries https://php.libhunt.com/libs/encryption
- using magic words within MediaWiki articles <encryption header for "wallet address">private key used for this revision</encryption header for "wallet address"><cypher>encryption text</cypher> for spotting encryption and calling the encryption handler which should be separate MW extension "Wallet Page Encryption" to have separation of concerns
-  there is a trade-off consideration between the amount of decrypt requests handled by the user and the security we provide; it might be too much to ask to decrypt every revision by the wallet. BUT I would recommend to outsource this into the config AS it is the 'clean' way to encrypt every revision seperatly. 
 - option: use one private-key per revision (highest level of security) OR use one private-key per page (more convenient) 
- single-user vs multi-user encryption: it is simple to add 'permissions to have multiple users being able to decrypt one revision, it just add's more headers. One header per  permissioned user.
- a new interface is required to enable / disable encryption for a page and to add new allowed users wallet addresses and inject it into the page
- the encryption handler needs to intercept the page load to replace the visible content as decrypted content and wise versa. The diff feature of mediawiki needs to be revised to see how we can inject the decryption handler so that we can see older revisions as well. That might cause some headeggs.

**Comment by rht** [comment]
What is the reason this is not planned?
