### ISSUE TITLE
[Tweeki] Deactivate Toolbox - How? Redundancy

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#231]
![image](https://user-images.githubusercontent.com/45313235/147628007-b20da171-cd73-4661-980e-a42465e9194a.png)

We have redundancy with the tool box, which is also not displaying correctly. 
How can we deactivate it? Introduce an option to deactivate it?

![image](https://user-images.githubusercontent.com/45313235/147628086-abcb5dd2-6382-4ca2-9eb1-c28fa7ff85c1.png)

**Comment by thaider** [comment]
The sidebar's content is defined with the ```MediaWiki:Tweeki-sidebar-right``` system message. Could you check it's content? The incorrect display is strange. Could you pull the latest version from master and see if the problem persists? Is the display correct for the dropdown in the navbar?

**Comment by FantasticoFox** [comment]
EDIT-EXT,SIDEBAR, TOC

There is no 'Toolbox' indicator I'm aware off. Nothing I can remove. 
If I remove the SIDEBAR it also removes the TOOLBOX they seem to be interconnected.

**Comment by thaider** [comment]
Ah, I see. You have to edit ```MediaWiki:Sidebar``` and remove TOOLBOX there.

**Comment by rht** [comment]
This is the content of `Mediawiki:Sidebat`:
```
* Data Accounting
** Special:VerifiedExport|Export Verified Page
** Special:VerifiedImport|Import Verified Page
** Special:Witness|Domain Snapshot Generator
** Special:WitnessPublisher|Domain Snapshot Publisher
** Special:DataAccountingConfig|Data Accounting Configurator
```

**Comment by FantasticoFox** [comment]
So there is no TOOLBAR. We are lost. Please advice @thaider happy to do a remote session if it helps.

**Comment by FantasticoFox** [comment]
Adding more context
![image](https://user-images.githubusercontent.com/45313235/148480804-0cd1bcb1-4513-41be-98e0-990bccfe243b.png)

**Comment by FantasticoFox** [comment]
We hack it for interim solutions by injecting js code into the  MediaWiki:common.css to hide the toolbar. This is not a solution.

**Comment by vhs-dev** [comment]
quickfix https://github.com/inblockio/micro-PKC/commit/de194e96d9535bf89c3e59420e00b2451bedef31

improved markup semantics would help our selection targeting in the future. for example, the toolbar is using anchor tags when it would ideally be `button`. we should also look into utilizing the `custom.css` file from tweeki rather than patching `tweeki.css`.

**Comment by thaider** [comment]
I actually have no clue, where the TOOLBOX comes from. Is it possible that you have defined ```MediaWiki:Sidebar``` in a different language (e.g. ```MediaWiki:Sidebar/en```)?

Could you make sure, that ```MediaWiki:Sidebar``` is really used by Tweeki? Are changes in ```MediaWiki:Sidebar``` reflected in the “Data Accounting” dropdown?

One workaround would be to put the content of ```MediaWiki:Sidebar``` directly into ```Mediawiki:Tweeki-sidebar-right``` like this:

```
EDIT-EXT
Data Accounting
* Special:VerifiedExport|Export Verified Page
* Special:VerifiedImport|Import Verified Page
* Special:Witness|Domain Snapshot Generator
* Special:WitnessPublisher|Domain Snapshot Publisher
* Special:DataAccountingConfig|Data Accounting Configurator
TOC
```

**Comment by rht** [comment]
This is the content of `MediaWiki:Sidebar/en`:
```

* navigation
** mainpage|mainpage-description
** recentchanges-url|recentchanges
** randompage-url|randompage
** helppage|help-mediawiki
* SEARCH
* TOOLBOX
* LANGUAGES

```
I deleted the `TOOLBOX` here, with no change in the outcome.

**Comment by rht** [comment]
> Could you make sure, that MediaWiki:Sidebar is really used by Tweeki? Are changes in MediaWiki:Sidebar reflected in the “Data Accounting” dropdown?

Yes, I just re-tested it. Adding a random list element is shown in the sidebar right away.

**Comment by thaider** [comment]
should be fixed in v2.0.1

**Comment by rht** [comment]
@thaider I'm curious, how did you fix it?

**Comment by thaider** [comment]
The toolbox is added by MediaWiki automatically and I'm removing it again in the code [here](https://github.com/thaider/Tweeki/blob/ab76c5e29868186ca04f2e57af51a50bdc9cdc64/includes/TweekiTemplate.php#L601).

If you want to remove the toolbox also for other skins you could use the [SkinBuildSidebar hook](https://www.mediawiki.org/wiki/Manual:Hooks/SkinBuildSidebar).
