### ISSUE TITLE
[GUI] Content-Boxes look ugly / always visible

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#233]
![image](https://user-images.githubusercontent.com/45313235/147628261-92de38be-4694-450b-acb9-0d3336d8cb75.png)

Currently the content boxes look quite ugly. 
How can we improve the UX to only display more info on demand? 
How can we make them 'extendable on demand' and nice looking?

**Comment by it-spiderman** [comment]
i guess this can be closed now
