### ISSUE TITLE
transclusion-hashes is shown by default and are confusing for users

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#243]
- How can we make it nice looking? (important)
- Keeping multi-language support in mind for the future. (optional)
- Introduce a function to toggle it in / out for improved user experience? (important)
- How does it look in the print out? How to hide it in print out? (optional)

**Comment by FantasticoFox** [comment]
Reduced priority because of other 'high' issues => reduce to 'medium'

**Comment by it-spiderman** [comment]
Done in https://github.com/inblockio/mediawiki-extensions-Aqua/tree/slot-rendering

**Comment by FantasticoFox** [comment]
Well done!
