### ISSUE TITLE
CI tests fail due to changes in method signature for setProvides in Composer 2.2

### ISSUE THREAD

**Issue by pwirth** [inblockio/mediawiki-extensions-Aqua#244]
MediaWiki core creates error due to changes in method signature for setProvides in Composer 2.2
Ticket:
https://phabricator.wikimedia.org/T298261
Patch for REL1_37:
https://gerrit.wikimedia.org/r/c/mediawiki/core/+/749767/

**Comment by pwirth** [comment]
it should already run on the newest version of the branch
https://github.com/inblockio/DataAccounting/blob/main/.github/workflows/ci.yml#L136

**Comment by rht** [comment]
Temporarily fixed in micro-PKC with https://github.com/inblockio/docker-aqua-mediawiki/commit/5f611e55dfed463bd7f064243580949b74e41614. But this solution does not apply to DataAccounting repo.

**Comment by rht** [comment]
@pwirth I think we can do the same hack as https://github.com/inblockio/docker-aqua-mediawiki/commit/5f611e55dfed463bd7f064243580949b74e41614 in the CI here for now. And let's wait for a month to try again if we can close this issue with the real solution (waiting for MW's patch release).

**Comment by pwirth** [comment]
i added it to the running test branch, but it did not work:
https://github.com/inblockio/DataAccounting/pull/226
Same error as before. i am doing it wrong?

**Comment by rht** [comment]
@pwirth you need to bump the cache version, https://github.com/inblockio/DataAccounting/blob/d68a96a47066a6b2d9c6461d05ed9ca3648370f4/.github/workflows/ci.yml#L50.

**Comment by pwirth** [comment]
i changed the v3 to v4, but the issue still persists

**Comment by pwirth** [comment]
oke, thank you.
I got it all sorted out now:
https://github.com/inblockio/DataAccounting/pull/284
All green

**Comment by pwirth** [comment]
merged, test now works again
