### ISSUE TITLE
[Tweeki] modal is under the top of navbar

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#246]
@thaider We tried this:
```  bash
# Make sure modal is on top of navbar
do_edit MediaWiki:Tweeki.css '.oo-ui-windowManager-modal {z-index: 1031}' "Make sure modal has higher z-index than navbar"
```
``` bash
do_edit() {
    local page="$1"
    local content="$2"
    local message="$3"
    echo "$content" | php maintenance/edit.php -s "$message" -u "$WALLET_ADDRESS" "$page"
}
```
![image](https://user-images.githubusercontent.com/45313235/148012668-2185042b-10fb-49d2-a125-3f435e991d35.png)

**Comment by FantasticoFox** [comment]
Our fix solves it for this window:
![image](https://user-images.githubusercontent.com/45313235/148012967-bc46c7d6-78db-4e96-be7c-4c38c7c8c9ea.png)

**Comment by FantasticoFox** [comment]
@thaider

**Comment by FantasticoFox** [comment]
Any z-index: 1030 higher then this will do.

**Comment by thaider** [comment]
should be fixed in master with the following rule added:

```
.wikiEditor-toolbar-dialog {
  z-index: 1031 !important;
}
```

**Comment by FantasticoFox** [comment]
Update to new Tweeki release

**Comment by thaider** [comment]
new release v2.0.1 available

**Comment by FantasticoFox** [comment]
Implemented in the new container.
