### ISSUE TITLE
Some of the procedures in the tests are duplicated

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#253]
I wonder if they can be abstracted out.
E.g. https://github.com/inblockio/DataAccounting/blob/0e346cc5f2b3e65199b75570ea56ea3006a566af/tests/phpunit/integration/DAApiTest.php#L57-L97, https://github.com/inblockio/DataAccounting/blob/0e346cc5f2b3e65199b75570ea56ea3006a566af/tests/phpunit/integration/DAApiTest.php#L198-L232, and so on.

cc: @pwirth

**Comment by pwirth** [comment]
i could separate all api tests into their own test classes and maybe have an abstract parent for all of them, but since the api tests all
