### ISSUE TITLE
Add multi-language support / populate German translation

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#258]
As we demonstrate our product as part of a project for the German Public Sector we require a translation / language support for our solution. How can we ensure that we are compatible for language switch? What options of MW functionality can we use? i18 ...

**Comment by it-spiderman** [comment]
Yes, we need to use message keys for any user-facing text. These can then be translated to any language, and will automatically be shown in user-selected language.
DataAccounting does use message keys for many of the string, but i believe there are still some hardcoded english strings.

**Comment by pwirth** [comment]
we could close this for now. all ui should have keys and translations by now - excluding error messages. but these can be added later

**Comment by FantasticoFox** [comment]
Basic support was added in 2021
