### ISSUE TITLE
[Signature] Disable Inject Signature has no effect

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#292]
When disabling inject signature in the configuration the expected behavior would be that the visual signature is no longer written into the page. This is not the case. The signature is still written into the page.

This is important to be changed as we need in some circumstances (creation of identity claims) a flow which does not write a visual signature by default. So this option should be problematically be deactivated or there is a way to just sign with making an exception to the visual signature injection.

**Comment by rht** [comment]
Fixed in #310. Already tested.
