### ISSUE TITLE
Introduce visual seperator like <hr> to make a clearer seperation between content of page and additional verification data

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#294]
![image](https://user-images.githubusercontent.com/45313235/149430552-c14ddec0-33a3-49b9-82bf-7bf1de9cb943.png)

**Comment by it-spiderman** [comment]
Done https://github.com/inblockio/mediawiki-extensions-Aqua/commit/f4ef6c942245cdbbda17a81cb04e1025369c902b
