### ISSUE TITLE
[Tweeki] Navbar hides Visual Editor on scroll down

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#297]
![image](https://user-images.githubusercontent.com/45313235/149451420-f90177ba-15ce-4781-8675-65bc6fe733e0.png)

Expected behavior is, that the blocked by the Navbar and does not continue to scroll up until it's 'under' the navbar. @thaider

**Comment by thaider** [comment]
Could you please let me know the exact versions of MediaWiki and VisualEditor you're using so I can reproduce the problem?

**Comment by FantasticoFox** [comment]
Mediawiki 1.37.1 (in build version of Visual Editor). @thaider

**Comment by FantasticoFox** [comment]
I could not reproduce the bug with the current Tweeki release. Seems to work just fine.
