### ISSUE TITLE
When exporting a jpg file with no further content in the page it will fail

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#301]
![image](https://user-images.githubusercontent.com/45313235/149605722-52cbb75e-fa17-4d6a-b3ab-32e7196fa0c1.png)

Reproduce: Upload the following image and export the page
![636px-Abiturzeugnis_1](https://user-images.githubusercontent.com/45313235/149605769-e9c1949f-1ecf-46ab-89b7-93556e2d149b.jpg)
.

**Comment by rht** [comment]
If this were Typescript, it would have been caught early on via static analysis because the return type of `newTransferContextFromTitle` is nullable. Is it possible to enable such checking with Psalm / PHPCS?

**Comment by FantasticoFox** [comment]
Could not reproduce.
