### ISSUE TITLE
Immutable links: when the page does not exist, it is somehow shown to be "up to date"

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#302]
To reproduce, simply create an immutable link to a non-existing page, and then un-collapse the transcluded resources content
![2022-01-14-214152_831x505_scrot](https://user-images.githubusercontent.com/395821/149605997-a0661e79-784f-42a4-ba04-5a670356978d.png)

**Comment by it-spiderman** [comment]
Also done in https://github.com/inblockio/mediawiki-extensions-Aqua/pull/309/files

This was showing "up to date" becuase no change happened since the transclusion map was created, page was missing then, its still missing, so "up to date".
With this change it will say "Page does not exist"

**Comment by FantasticoFox** [comment]
Was done!
