### ISSUE TITLE
Imported files which exist are not skipped as expected.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#304]
![image](https://user-images.githubusercontent.com/45313235/149609171-5ba38978-087e-491a-994c-fee613c07b2e.png)

Expected behavior would be: Same file exist, file not imported.
Only if verification history of imported file is longer, delete local one and import the new file.

**Comment by it-spiderman** [comment]
https://github.com/inblockio/mediawiki-extensions-Aqua/pull/312
