### ISSUE TITLE
When verification data is wiped (on purpose) the transclusion hashes all break (understandably) but should not throw error -> how to recover?

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#307]
![image](https://user-images.githubusercontent.com/45313235/149610471-26480c6a-26a1-46f4-a134-b6943b919d3d.png)

**Comment by FantasticoFox** [comment]
Recreate a page identity should be the right way... as the old one has been destroyed.

The bug that a transcluded resource with no verification data causes a crash should anyway be circumvented.
Good to provide a new status: No verification data (on the slot).

**Comment by it-spiderman** [comment]
https://github.com/inblockio/mediawiki-extensions-Aqua/pull/309/files
