### ISSUE TITLE
testCalculateMetadataHash is not actually testing calculateMetadatahash

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#308]
https://github.com/inblockio/mediawiki-extensions-Aqua/blob/94cf067605044c09da51f9cd7ebebbb7ca9e42d3/tests/phpunit/Unit/HashingServiceTest.php#L46
it is actually doing its own hardcoded metadata calculation, which happens to be the same as https://github.com/inblockio/mediawiki-extensions-Aqua/blob/94cf067605044c09da51f9cd7ebebbb7ca9e42d3/includes/Verification/VerificationEngine.php#L219, but the latter is not actually wrapped in a function and tested.

Solution: should define `calculateMetadataHash` and test the function instead.

**Comment by rht** [comment]
I just discovered the same problem exists with `testCalculateWitnessHash`, and other hashes.
They all seem to be originated from this commit, https://github.com/inblockio/mediawiki-extensions-Aqua/commit/6c627b9616e82e037b733cd78b90486c9b609760. cc @it-spiderman

**Comment by rht** [comment]
@it-spiderman is there a way to define e.g. `calculateWitnessHash` such that 1. the arguments must be keyword arguments, and 2. the order of the arguments does not matter?

**Comment by it-spiderman** [comment]
i dont undestand your point, what is the difference between
```
$this->getHasher()->getHashSum(
			$this->getDomainId() . $timestamp . $previousVerificationHash
		);
```
and 
```
function getMetadataHash( $domain, $timestamp, $pvh ) {
       return $this->getHashSum( $domain . $timestamp . $pvh );
}

// Call
$this->getHasher()->getMetadataHash( $this->getDomainId(), $timestamp, $previousVerificationHash)
```

Since only real method here is `getHashSum` that is the only thing that needs testing, all other depend on what you pass to it

**Comment by rht** [comment]
Because the order of the concatenation is part of the metadata hash specification. Ideally, the caller of the function `getMetadataHash` should not need to specify the order of the arguments, because this is error prone. It is better to make the function arguments to be order-independent.

**Comment by it-spiderman** [comment]
not really. Only we, from the extension call this function, so we can make sure to follow the order as much as if we had a dedicated function. But even with a function, you can only control order in which you use arguments, but caller could still switch order of params in the call, since they are all strings. 
It would make sense if you could pass like `VerificationEntity`, and then all data is pulled and ordered from there, but without looking in the code i cannot say if that is possible
