### ISSUE TITLE
MW's `select` and `selectRow` always return string

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#311]
Some of the column types are e.g. `INT(32)` for `depth` in `witness_merkle_tree`. We should always cast them away from being string whenever applicable. Resolving this issue means that we have to remove the usage of wildcard select `['*']`.

**Comment by pwirth** [comment]
a PR is ready here: https://github.com/inblockio/mediawiki-extensions-Aqua/pull/313

**Comment by pwirth** [comment]
PR was merged
