### ISSUE TITLE
[FEATURE] Update Transclusion logic to allow to link to specific revision_verification hash.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#314]
Currently it will auto-select the latest version of a page, if a page is newly created.
How can I 'downgrade to a earlier revision via the revision hash?'. 

As a user, I can choose to select a specific revision to link to. Paste the verification hash of that page and I'll link to this specific revision.

**Comment by it-spiderman** [comment]
I would definitelly not do this in the content (not like {{SomePage|i39234...32343}} ). This will make it a hell for updating and controlling as it would require parsing the content.
I would suggesting creating an UI that would allow you to manípulate `transclusion-hashes` slot. Whatever VH is specified there is the version that will be included.

**Comment by FantasticoFox** [comment]
I agree. This will increase in priority with managing the postbox and incoming data.
Let's ensure we have a design session before moving into implementation of any functionality on this.

**Comment by it-spiderman** [comment]
As a natural consequence of https://github.com/inblockio/mediawiki-extensions-Aqua/issues/327, this will also be possible.
For design aspects, we can do more work.

**Comment by FantasticoFox** [comment]
Is still open, will not be changed for now.
