### ISSUE TITLE
Stateful links

### ISSUE THREAD

**Issue by it-spiderman** [inblockio/mediawiki-extensions-Aqua#327]
Make sure links included in pages are tracked, like transclusions and files, and to be able to visit specific version of the page based on its verification hash

**Comment by it-spiderman** [comment]
Implementation done in https://github.com/inblockio/mediawiki-extensions-Aqua/tree/stateful_links

How it behaves:
- Linking to a page will include its verification hash in the `transclusion-hashes` slot, same as for transclusions and files
- Clicking on the those links inside the page will open the page with `version` param in the URL which will allow to view old version of the page based on the hash

New things:
- Transclusion hashes section got some changes => now you have two links there, one to see the included version and another to see the latest version. 
- Pages can now be accessed by verification_hash, by adding `version` param (http://localhost/index.php/MyPage?version=2334....9asxd90s

Drawbacks:
Unlike templates and files, which will appear in `transclusion-hashes` section only if they are directly used on the page (not transclusion of a transclusion), links will all (even transcluded deeper down the line) appear as transcluded on the page. Reason for this are:
- Its impossible to reliably determine which links are linked in the page itself and which come from sub-transclusions
- We need verification_hash of every link that user sees on the page, even if it comes from a sub-transclusion, to be able to modify the link to include the verification_hash. Traversing through the translusion tree to see which resource includes this link is practically impossible for each link.

Implementation is pretty much done, but not mergeable yet.

**Comment by FantasticoFox** [comment]
The Domain Snapshot fails in this branch.

![image](https://user-images.githubusercontent.com/45313235/150739086-5c6489b1-f86b-4163-8899-ce3af1295954.png)
