### ISSUE TITLE
Passing page title to API endpoint

### ISSUE THREAD

**Issue by it-spiderman** [inblockio/mediawiki-extensions-Aqua#335]
API has to be passed the english page name. If you pass Vorlage:Test to an english PKC it has no way of figuring out what this is, no matter what we do

if you call API like this `http://localhost:9352/rest.php/data_accounting/get_hash_chain_info/title?identifier=Vorlage:Test`, it will only work if PKC's language is german. If its set to any other language, it wont be able to recognize what Vorlage is, and will return 404. That is why i said that page title params passed to API must always be english (Template:Test)

**Comment by FantasticoFox** [comment]
Known Limitation
