### ISSUE TITLE
The "I sign the following page verification_hash ..." sentence might require "hereby"

### ISSUE THREAD

**Issue by rht** [inblockio/mediawiki-extensions-Aqua#344]
IANAL, but see https://weagree.com/drafting-principles/6-typical-drafting-habits-and-legalese/6-1-certain-funny-phrases/l-hereby/.

**Comment by FantasticoFox** [comment]
Also we sign a revision verification hash. Formerly 'page'.

**Comment by FantasticoFox** [comment]
"I hereby sign the following revision verification hash:"

**Comment by FantasticoFox** [comment]
Prototype.
