### ISSUE TITLE
[degradation] Upgrading to MW1.39 causes the Witness Generator to fail

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#352]
https://github.com/inblockio/mediawiki-extensions-Aqua/commits/rewrite_revision_history/

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/07befd7a-013d-4c3e-a357-a5c8d668931e)

**Comment by it-spiderman** [comment]
Fixed with https://github.com/inblockio/aqua-PKC/pull/128

**Comment by FantasticoFox** [comment]
It works now! Thank you.
