### ISSUE TITLE
[FEATURE] Have a fork button which creates a copy of an article 

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#357]
Userstory: I want to be able to create a "copy" / "fork" of a page, which allows me to have two or more different versions of an article. This allows me to e.g. use templates with the same origin (Genesis hash) which can be the foundation to system contracts which can be enforced by the guardian. Like a data access agreement which we can use to give permissions to share a file through the guardian.

Technical: Most likely similar to the "move" action without removing it's source. We need to have a useful way to relate to the different forks. This might be something we need to discuss, whats the best strategy to organise the datasets @it-spiderman @mrglaser

**Comment by it-spiderman** [comment]
Done in https://github.com/inblockio/mediawiki-extensions-Aqua/pull/369
