### ISSUE TITLE
API Documentation with the code (Documentation close ot the code we can link)

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#358]
- We should have a clear documentation what is possible with the current API's and how to use them for third parties to integrate with it.
- In this case we are the third party ;-) and we need to integrate against the Guardian

**Comment by it-spiderman** [comment]
Added OpenAPI docu in https://github.com/inblockio/mediawiki-extensions-Aqua/pull/365
You can open this file in https://editor.swagger.io/ for example
