### ISSUE TITLE
Import API does not throw error with empty valus being imported leading to data corruption

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#360]
Specific example: remove verification hash in latest

Expected behavior: Throw error.

Additionally the verification hash is used from the wrong location within the data structure.
verification_hash in metadata does not meet specification. https://aqua-protocol.org/docs/protocol/whitepaper/#metadata

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/459780ed-1854-4be4-be7f-6f9aef933701)

**Comment by it-spiderman** [comment]
will be done with https://github.com/inblockio/mediawiki-extensions-Aqua/pull/382
