### ISSUE TITLE
Reduce noise for empty-signature in export

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#361]
{
"signature": null, // instead of object with all empty strings
}

This helps us to keep the code clean on the guardian side. Please help us to iterate through the different aspects of the output to reduce it to minimum.

**Comment by FantasticoFox** [comment]
null signature was reverted as it was buggy.

**Comment by FantasticoFox** [comment]
Current export of the default main page after deployment:

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/d85dc044-8110-4197-aedd-c5d3cd9ea8d4)

Expected output, important if its genesis revision it should also hold a null value.

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/a309ff2a-7fa7-40f1-baaa-b9a471f1a710)

**Comment by it-spiderman** [comment]
Done in https://github.com/inblockio/mediawiki-extensions-Aqua/pull/374

Export/import in PKC works.
However, i could not test with extenal verifier, as i dont know how to get this patch into my extension
https://github.com/inblockio/aqua-verifier-js/pull/21

I tried removing and re-installing the Chrome ext, but didnt help
With this patch, verifier should presumably work, but needs to be tested before PR is merged

**Comment by FantasticoFox** [comment]
Please check with the current release 1.2.6 which supports the null value.
https://chromewebstore.google.com/detail/verifypage/gadnjidhhadchnegnpadkibmjlgihiaj?hl=en-GB

**Comment by FantasticoFox** [comment]
I tested it and it works fine with the current VerifyPage release. Thank you.

**Comment by FantasticoFox** [comment]
Re-open due to https://github.com/inblockio/mediawiki-extensions-Aqua/issues/376

**Comment by it-spiderman** [comment]
To be closed when #376 is closed
