### ISSUE TITLE
[New API Endpoint] get_branch

### ISSUE THREAD

**Issue by rhe3565** [inblockio/mediawiki-extensions-Aqua#375]
Aqua chains allow for forking. This means there can be multiple aqua chains originating from one genesis hash(getting an aqua chain from a genesis hash would therefore have to return all branches). getting an aqua-chain from its page_name is possible, but not ideal, as the name of a page can be changed arbitrarily.
For this reason the best way of getting an aqua chain would be by its latest revision_hash. There is currently no such api-call. This api-call would return an aqua chain with all its revisions from its first revision to the latest revision(on the relevant branch).

Ideally this call would work exactly as get_page_all_revs does but take the last revision hash rather than the page title. (the return type would remain the same)

**Comment by it-spiderman** [comment]
I have adapted `get_page_all_revs` to accept both title and verification hash (as both APIs are basically the same).
Specifying either will now return proper chain, also for forked pages 

https://github.com/inblockio/mediawiki-extensions-Aqua/commit/2a3e4071bf3161a9d388f1a24ddf90d1225f4e3d

**Comment by FantasticoFox** [comment]
In addition to the return we need:

page_info:
{
title,
namespace: as integer
}

for the impor context.

**Comment by it-spiderman** [comment]
Yes, this endpoint returns `VerificationEntites` which already contain this info. or do you need it in exactly this format?

**Comment by FantasticoFox** [comment]
I reviewed the code with one of my team members who was really upset about this solution. He was not happy that a page containing 128 characters would not be handled if inputted into the API. Additionally, he noted that the namespace is missing.

We would like to have a robust solution which includes a separate API endpoint that receives only the hash as an input. There is a draft for this here: https://github.com/inblockio/mediawiki-extensions-Aqua/pull/394, which is working according to my colleague.

Our tests are following this shema:
![IMG_9584](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/9fa6ac7f-fa73-4286-9ec0-0ef8a16b5cf5)

**Comment by FantasticoFox** [comment]
@it-spiderman could you please review the PR to ensure its working as expected?
