### ISSUE TITLE
After null signature patch: Import broken 

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#376]
![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/5dad7c55-da28-4b33-9846-87d7bf5c4018)

**Comment by FantasticoFox** [comment]
[2be379f4ba_Demo_Pages.json](https://github.com/inblockio/mediawiki-extensions-Aqua/files/15483653/2be379f4ba_Demo_Pages.json)

Please check with this, same error still occurs.

**Comment by danielriedmueller** [comment]
Being on main branch, import of demo pages works:
![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/5981468/1d64882b-26a2-4311-8ff1-598e210e8fbe)

**Comment by FantasticoFox** [comment]
I tested in the current release where it is included and it works.

There is a prefix added to the file "File" which leads to the file namespace being extended by "File:File:" I would assume that this is not intended behavior, and would be nice to fix before closing the issue.

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/cb443683-5361-4be3-9e0b-871e9b3d3d11)
