### ISSUE TITLE
[Regression] OIDC-Userbug with numbering returns

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#378]
We changed the way how our images are build, but for some reason the bug returned which introduces the 1 / 2 numberings in the end. For some reason the patch is not working anymore when deploying web-public, unclear why.

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/f2a12d2f-4bf4-4920-aea7-fbdd6ba1e4a2)

**Comment by it-spiderman** [comment]
Fresh pulled aqua-PKC, nuke, setup, patch is applied, no issue found

**Comment by FantasticoFox** [comment]
I did the same and could not reproduce the bug. Must have been the old instance I used for demo.
