### ISSUE TITLE
[New API Endpoint] get_recent_changes

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#383]
/data_accounting/get_recent_changes?since={timestamp}
        all hashes which have been created or deleted since {timestamp}

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/f38dfc83-d954-481b-8e0b-1b2b62a3e913)

**Comment by FantasticoFox** [comment]
Not needed anymore as we can use recent_changes from mediawiki standard API.

**Comment by FantasticoFox** [comment]
How to keep track of deleted revisions?

One hack could be:

- {[hash]: change }
- change:: = delete, sign, witness, create

**Comment by it-spiderman** [comment]
See https://github.com/inblockio/mediawiki-extensions-Aqua/pull/406
