### ISSUE TITLE
[Guardian Session Token] Guardian User is not created during setup / should use wallet address

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#387]
```bash
Database was successfully set up
MediaWiki has been successfully installed. You can now visit <http://localhost:9352> to view your wiki. If you have questions, check out our frequently asked questions list: <https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:FAQ> or use one of the support forums linked on that page.
Could not open input file: extensions/DataAccounting/maintenance/createSysopUser.php
Guardian security token is: aVk4NmpLUXpFWFFlYnhJcDI1MU90QkxkODFtNGpIUk4=
Set guardian token in LocalSettings.php
```

I belief this is the case because the OIDC connect is already configured therefor the context to create the User is not available anymore.

This is related to this commit: https://github.com/inblockio/aqua-PKC/commit/5f8b48870da5cebcf09ba24d61c18f80065b8032

the file inquestion is in aqua-PKC/aqua/install_pkc.sh

**Comment by FantasticoFox** [comment]
In this branch, I generate an ethereum wallet, and removed the token generation logic

https://github.com/inblockio/aqua-PKC/pull/new/guardian_wallet_gen

The code is not functional but should illustrate the required changes.
![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/347b7111-11ec-42e1-b7a0-5d1fe5f624b6)

Please provide us with a way to continue to use the create and promote user scripts if possible as we also used them for automated demo-generation and user deployment based on their public keys (random passwords) as login is later done via SIWE-OIDC anyways.

**Comment by danielriedmueller** [comment]
Script was in wrong folder. Should work now.
