### ISSUE TITLE
[Inbox] not shown in the recent-changes API

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#388]
We want to treat the inbox as any other page in the PKC, we need to see the pages that they have been imported so the Guardian is aware of it.

**Comment by it-spiderman** [comment]
Fixed with https://github.com/inblockio/mediawiki-extensions-Aqua/commit/2bde1484f68b3bbd985e7590986657a386eb81a6

**Comment by FantasticoFox** [comment]
Tested and works.
