### ISSUE TITLE
[Main Branch] [Creating new revisions should be very limited]

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#389]
We don't want to create new revisions on import, or on move because:

- Guardian Contract validation logic becomes more complex
- Files which are imported are all "outdated" as every file now links to a new revision which is causes the user to think that the data has been changed (which it was because of the new revision).
- Causes additional load on the Guardian, as every revision gets verified
- Every new revision is shared based on Data-Access-Agreements

**Comment by it-spiderman** [comment]
Importing non-existing page from Inbox will no longer create additional revisions => 
https://github.com/inblockio/mediawiki-extensions-Aqua/pull/368
Other cases (when local target page already exists) will be handled much like git, with a "merge" revision created on top of last local revision

**Comment by it-spiderman** [comment]
Merged
