### ISSUE TITLE
[Import][Bug] On import one revision does not show up

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#393]
When importing the attached JSON I expect 3 revisions. But only 2 make into the inbox.

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/de7903bd-6e09-4275-8388-79a929728af7)

![image](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/45313235/fe29acc2-48ed-42b7-a6de-c26e2af57cb3)

[647403dbf7_DAATest.json](https://github.com/user-attachments/files/15592090/647403dbf7_DAATest.json)

**Comment by it-spiderman** [comment]
It already works in the latest `main`. Please confirm.
Note: This export file has key for the siteinfo set as `siteInfo`, which is changed in main. So if you want to import this file into a PKC@main, change that to `site_info`
