### ISSUE TITLE
Importing pages which are already in the PKC causes a Database error

### ISSUE THREAD

**Issue by Multiiiiii** [inblockio/mediawiki-extensions-Aqua#409]
![active2024-06-29 14:06:05](https://github.com/inblockio/mediawiki-extensions-Aqua/assets/149270406/8ede2413-49a8-497e-b932-9b037026c200)

**Comment by FantasticoFox** [comment]
Dublicate of https://github.com/inblockio/mediawiki-extensions-Aqua/issues/399
